import type { Metadata } from "next";
import { Kanit } from "next/font/google";
import "./globals.css";

const kanit = Kanit({
  weight: ["400"],
  variable: "--font-kanit",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Class Room EP105",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${kanit.variable} ${kanit.variable} antialiased`}>
        {children}
      </body>
    </html>
  );
}
